routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route: Route::get('/home', 'HomeController@index');

Route::middleware(['auth'])->group(function() {

  Route::resource('companies', 'CompaniesController');
  Route::get('projects/create/{company_id?}', 'ProjectsController@create'); // ? means id is optional
  Route::resource('projects', 'ProjectsController');
  Route::resource('roles', 'RolesController');
  Route::resource('tasks', 'TasksController');
  Route::resource('users', 'UsersController');
  Route::resource('comments', 'CommentsController');
  Route::resource('banklists', 'BanklistsController');

});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
  protected $fillable = [
    'name',
    'description',
    'company_id',
    'user_id',
    'days'
  ];

  public function user() {
    return $this->belongsToMany('App\User');
  }

  public function company() {
    return $this->belongsTo('App\Company');
  }

  public function comments() {
    return $this->morphMany('App\Comment', 'commentable');
  }

}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use App\Company;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ProjectsController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    if(Auth::check()){

      $projects = Project::where('user_id', Auth::user()->id)->get();

      return view('projects.index', ['projects'=> $projects]);
    }

    return view('auth.login');
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create($company_id = null)
  {
      $companies = null;

      if(!$company_id) {
        $companies = Company::where('user_id', Auth::user()->id)->get();
      }

      return view('projects.create', ['company_id'=>$company_id, 'companies'=>$companies]);
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
      if(Auth::check()) {
        $project = Project::create([
          'name' => $request->input('name'),
          'description' => $request->input('description'),
          'company_id' => $request->input('company_id'),
          'user_id' => Auth::user()->id
        ]);

        if($project) {
          return redirect()->route('projects.show', ['project'=> $project->id])
            ->with('success', 'project created successfully!');
        }
      }

        return back()->withInput()->with('errors', 'Error creating new project');
  }

  /**
   * Display the specified resource.
   *
   * @param  \App\project  $project
   * @return \Illuminate\Http\Response
   */
  public function show(Project $project)
  {
      //

      //$project = Project::where('id', $project->id)->first();
      $project = Project::find($project->id);

      return view('projects.show', ['project'=>$project]);
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  \App\project  $project
   * @return \Illuminate\Http\Response
   */
  public function edit(Project $project)
  {
    $project = Project::find($project->id);

    return view('projects.edit', ['project'=>$project]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  \App\project  $project
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, Project $project)
  {
      //save data
      $projectUpdate = Project::where('id', $project->id)->update([
        'name'=> $request->input('name'),
        'description'=> $request->input('description')
      ]);

      if($projectUpdate) {
        return redirect()->route('projects.show', ['project'=>$project->id])
          ->with('success', 'project updated successfully!');
      }

      return back()->withInput();
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  \App\project  $project
   * @return \Illuminate\Http\Response
   */
  public function destroy(Project $project)
  {
      $findproject = Project::find($project->id);

      if($findproject->delete()) {
        return redirect()->route('projects.index')
          ->with('success', 'project deleted successfully!');
      }

      return back()->withInput()->with('error', 'project could not be deleted!');
  }
}

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('content')
      <!-- Jumbotron -->
  <div class="col-md-9 col-lg-9 col-sm-9 pull-left" style="background: white;">
    <h1>Create new project</h1>

        <!-- Example row of columns -->
    <div class="row col-lg-12 col-md-12 col-sm-12" style="background: white; margin: 10px;">

      <form method="post" action="{{ route('projects.store') }}">
        {{ csrf_field() }}

        <div class="form-group">
          <label for="project-name">Name<span class="required">*</span></label>
          <input placeholder="Enter name"
                id="project-name"
                required
                name="name"
                spellcheck="false"
                class="form-control" />
        </div>

        <input type="hidden" name="company_id" value="{{ $company_id }}" />

        @if($companies != null)
        <div class="form-group">
          <label for="company-content">Select company</label>
          <select name="company_id" class="form-control">
            @foreach($companies as $company)
            <option value="{{ $company->id }}">
              {{ $company->name }}
            </option>
            @endforeach
          </select>

        </div>
        @endif

        <div class="form-group">
          <label for="project-content">Description</label>
          <textarea placeholder="Enter description"
                style="resize: vertical"
                id="project-content"
                rows="5"
                name="description"
                spellcheck="false"
                class="form-control autosize-target text-left"></textarea>
        </div>

        <div class="form-group">
          <input type="submit" class="btn btn-primary" value="Submit" />
        </div>

      </form>

    </div>
  </div>


  <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
          <!-- <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div> -->
          <div class="sidebar-module">
            <h4>Manage</h4>
            <ol class="list-unstyled">
              <li><a href="/projects">List of projects</a></li>
            </ol>
          </div>

          <!-- <div class="sidebar-module">
            <h4>Members</h4>
            <ol class="list-unstyled">
              <li><a href="#">Amira</a></li>
            </ol>
          </div> -->
        </div>
    @endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('content')
      <!-- Jumbotron -->
  <div class="col-md-9 col-lg-9 col-sm-9 pull-left" style="background: white;">
    <h1>Edit project</h1>

        <!-- Example row of columns -->
    <div class="row col-lg-12 col-md-12 col-sm-12" style="background: white; margin: 10px;">

      <form method="post" action="{{ route('companies.update', [$company->id]) }}">
        {{ csrf_field() }}

        <input type="hidden" name="_method" value="put" />

        <div class="form-group">
          <label for="company-name">Name<span class="required">*</span></label>
          <input placeholder="Enter name"
                id="company-name"
                required
                name="name"
                spellcheck="false"
                class="form-control"
                value="{{ $company->name }}" />
        </div>

        <div class="form-group">
          <label for="company-content">Description</label>
          <textarea placeholder="Enter description"
                style="resize: vertical"
                id="company-content"
                rows="5"
                name="description"
                spellcheck="false"
                class="form-control autosize-target text-left">
                {{ $company->description }}</textarea>
        </div>

        <div class="form-group">
          <input type="submit" class="btn btn-primary" value="Submit" />
        </div>

      </form>

    </div>
  </div>


  <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
          <!-- <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div> -->
          <div class="sidebar-module">
            <h4>Manage</h4>
            <ol class="list-unstyled">
              <li><a href="/companies/{{ $company->id }}">View companies</a></li>
              <li><a href="/companies">All companies</a></li>
            </ol>
          </div>

          <!-- <div class="sidebar-module">
            <h4>Members</h4>
            <ol class="list-unstyled">
              <li><a href="#">Amira</a></li>
            </ol>
          </div> -->
        </div>
    @endsection

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('content')

<div class=" col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3">
  <div class="panel panel-primary">
    <div class="panel-heading">Projects <a class="pull-right btn btn-primary btn-sm" href="/projects/create">Add Project</a></div>
    <div class="panel-body">

      <ul class="list-group">
        @foreach($projects as $project)
        <li class="list-group-item"><a href="/projects/{{ $project->id }}">{{ $project->name }}</a></li>
        @endforeach
      </ul>

    </div>
  </div>
</div>

@endsection

resources/views/projects/show.blade.php
@extends('layouts.app')

@section('content')
      <!-- Jumbotron -->
  <div class="col-md-9 col-lg-9 col-sm-9 pull-left">
    <div class="well well-lg">
      <h1>{{ $project->name }}</h1>
      <p class="lead">{{ $project->description }}</p>
      <!-- <p><a class="btn btn-lg btn-success" href="#" role="button">Get started today</a></p> -->
    </div>

        <!-- Example row of columns -->
      <div class="row" col-sm-12 col-md-12 col-lg-12 style="background: white; margin: 15px; padding: 10px;">
        <!-- <a href="/projects/create" class="pull-right btn btn-default btn-sm">Add Project</a><br /> -->

      <div class="row container-fluid">
        <form method="post" action="{{ route('comments.store') }}">
          {{ csrf_field() }}

          <input type="hidden" name="commentable_type" value="App\Project" />
          <input type="hidden" name="commentable_id" value="{{ $project->id }}" />

          <div class="form-group">
            <label for="comment-content">Comment</label>
            <textarea placeholder="Enter comment"
                  style="resize: vertical"
                  id="comment-content"
                  rows="3"
                  name="body"
                  spellcheck="false"
                  class="form-control autosize-target text-left"></textarea>
          </div>

          <div class="form-group">
            <label for="comment-content">URL (proof of work done)</label>
            <textarea placeholder="Enter URL or photo(s)"
                  style="resize: vertical"
                  id="comment-content"
                  rows="2"
                  name="url"
                  spellcheck="false"
                  class="form-control autosize-target text-left"></textarea>
          </div>

          <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Submit" />
          </div>

        </form>
      </div>


        @foreach($project->comments as $comment)
        <div class="col-lg-4 col-md-4 col-sm-4">
          <h2>{{ $comment->body }}</h2>
          <p class="text-danger">{{ $comment->url }}</p>
        </div>
        @endforeach
      </div>
  </div>


  <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
          <!-- <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div> -->
          <div class="sidebar-module">
            <h4>Manage</h4>
            <ol class="list-unstyled">
              <li><a href="/projects/{{ $project->id }}/edit">Edit</a></li>
              <li><a href="/projects/create">Add Project</a></li>
              <li><a href="/projects/">List of projects</a></li><br />
              @if($project->user_id == Auth::user()->id)
              <li><a href="#"
                      onclick="
                              var result = confirm('Are you sure to delete {{ $project->name }} project?');

                                if(result) {
                                  event.preventDefault();
                                  document.getElementById('delete-form').submit();
                                }">Delete</a>

                  <form id="delete-form"
                        action="{{ route('projects.destroy', [$project->id]) }}"
                        method="POST"
                        style="display: none;">

                    <input type="hidden" name="_method" value="delete" />
                    {{ csrf_field() }}
                  </form>
              </li>
              @endif

              <!-- <li><a href="#">Add new member</a></li> -->
            </ol>
          </div>

          <!-- <div class="sidebar-module">
            <h4>Members</h4>
            <ol class="list-unstyled">
              <li><a href="#">Amira</a></li>
            </ol>
          </div> -->
        </div>
    @endsection